"""Goal segmentation: the arc of a session, reconstructed from its transcript."""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from asm import codex_session_parser, goals, session_parser


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.write_text("\n".join(json.dumps(record) for record in records) + "\n", encoding="utf-8")


def user(text: str, ts: str) -> dict:
    return {"type": "user", "timestamp": ts, "uuid": ts,
            "message": {"role": "user", "content": [{"type": "text", "text": text}]}}


def tool_result(call_id: str, ts: str, *, error: bool = False) -> dict:
    return {"type": "user", "timestamp": ts, "uuid": ts + "-r", "message": {
        "role": "user",
        "content": [{"type": "tool_result", "tool_use_id": call_id, "content": "out", "is_error": error}],
    }}


def assistant(ts: str, blocks: list[dict], *, message_id: str, model: str = "claude-opus-4-8") -> dict:
    return {"type": "assistant", "timestamp": ts, "uuid": ts + "-a", "message": {
        "role": "assistant", "id": message_id, "model": model, "content": blocks,
        "usage": {"input_tokens": 100, "output_tokens": 50,
                  "cache_read_input_tokens": 900, "cache_creation_input_tokens": 0},
    }}


def tool_use(name: str, call_id: str, **inp) -> dict:
    return {"type": "tool_use", "id": call_id, "name": name, "input": inp}


class CategoryTests(unittest.TestCase):
    def test_known_tools_land_in_the_expected_category(self) -> None:
        cases = {
            "Read": "read", "Grep": "search", "Glob": "search", "Edit": "edit",
            "MultiEdit": "edit", "Write": "edit", "Bash": "exec", "WebFetch": "web",
            "Agent": "agent", "Task": "agent", "TodoWrite": "plan",
            "AskUserQuestion": "ask", "SendMessage": "agent", "TaskCreate": "plan",
        }
        for name, expected in cases.items():
            self.assertEqual(goals.categorize(name), expected, name)

    def test_mcp_tools_are_their_own_category(self) -> None:
        self.assertEqual(goals.categorize("mcp__company-kb__kb_search"), "mcp")

    def test_an_unknown_tool_is_placed_by_what_its_name_says(self) -> None:
        self.assertEqual(goals.categorize("acme_file_search"), "search")
        self.assertEqual(goals.categorize("run_shell_thing"), "exec")
        self.assertEqual(goals.categorize("totally_novel"), "other")

    def test_every_category_is_declared(self) -> None:
        """The frontend legend is keyed off CATEGORIES; nothing may escape it."""
        for name in ("Read", "Grep", "Edit", "Bash", "WebFetch", "Agent",
                     "TodoWrite", "AskUserQuestion", "mcp__x__y", "totally_novel"):
            self.assertIn(goals.categorize(name), goals.CATEGORIES)


class PromptClassificationTests(unittest.TestCase):
    def test_a_slash_command_survives_its_wrapper(self) -> None:
        kind, text = goals.classify_prompt("<command-message>init</command-message> <command-name>/init</command-name>")
        self.assertEqual((kind, text), ("command", "/init"))

    def test_cli_scaffolding_is_not_a_prompt(self) -> None:
        for noise in ("<local-command-stdout>ls</local-command-stdout>",
                      "<system-reminder>be good</system-reminder>",
                      "Caveat: the messages below were generated by the user",
                      "<environment_context>cwd</environment_context>",
                      "# Files mentioned by the user: foo.png"):
            self.assertEqual(goals.classify_prompt(noise)[0], "noise", noise)

    def test_a_real_prompt_is_flattened_to_one_line(self) -> None:
        kind, text = goals.classify_prompt("  fix the\n\n  parser  \n")
        self.assertEqual(kind, "prompt")
        self.assertEqual(text, "fix the parser")


class ClaudeGoalTests(unittest.TestCase):
    def build(self, records: list[dict]) -> dict:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "session.jsonl"
            write_jsonl(path, records)
            return session_parser.detail(path)["goals"]

    def test_one_goal_per_prompt_and_tool_results_do_not_start_one(self) -> None:
        result = self.build([
            user("first request", "2026-08-01T10:00:00.000Z"),
            assistant("2026-08-01T10:00:05.000Z", [tool_use("Read", "t1", file_path="/a/b.py")], message_id="m1"),
            tool_result("t1", "2026-08-01T10:00:06.000Z"),
            assistant("2026-08-01T10:00:09.000Z", [{"type": "text", "text": "done"}], message_id="m2"),
            user("second request", "2026-08-01T10:05:00.000Z"),
            assistant("2026-08-01T10:05:30.000Z", [tool_use("Bash", "t2", command="pytest -q")], message_id="m3"),
            tool_result("t2", "2026-08-01T10:05:40.000Z"),
        ])
        self.assertEqual(result["count"], 2)
        first, second = result["goals"]
        self.assertEqual(first["prompt"], "first request")
        self.assertEqual(first["by_cat"], {"read": 1})
        self.assertEqual(first["turns"], 2)
        self.assertEqual(second["by_cat"], {"exec": 1})
        self.assertEqual(second["commands"], ["pytest"])

    def test_a_goal_measures_from_its_prompt_to_the_next_one(self) -> None:
        result = self.build([
            user("go", "2026-08-01T10:00:00.000Z"),
            assistant("2026-08-01T10:00:04.000Z", [{"type": "text", "text": "ok"}], message_id="m1"),
            assistant("2026-08-01T10:02:00.000Z", [{"type": "text", "text": "still going"}], message_id="m2"),
        ])
        goal = result["goals"][0]
        self.assertEqual(goal["ms"], 120_000)
        self.assertEqual(goal["latency_ms"], 4_000)

    def test_a_failing_tool_is_charged_to_the_goal_that_called_it(self) -> None:
        result = self.build([
            user("build it", "2026-08-01T10:00:00.000Z"),
            assistant("2026-08-01T10:00:02.000Z", [tool_use("Bash", "t1", command="make")], message_id="m1"),
            # The result lands after the user has already typed the next prompt.
            user("never mind", "2026-08-01T10:00:03.000Z"),
            tool_result("t1", "2026-08-01T10:00:05.000Z", error=True),
        ])
        first, second = result["goals"]
        self.assertEqual(first["errors"], 1)
        self.assertEqual(second["errors"], 0)
        self.assertEqual(first["error_names"], {"Bash": 1})
        self.assertTrue(first["steps"][0]["e"])

    def test_a_question_marks_the_goal_and_the_session(self) -> None:
        result = self.build([
            user("which one?", "2026-08-01T10:00:00.000Z"),
            assistant("2026-08-01T10:00:02.000Z", [tool_use("AskUserQuestion", "t1")], message_id="m1"),
            tool_result("t1", "2026-08-01T10:00:20.000Z"),
        ])
        goal = result["goals"][0]
        self.assertTrue(goal["asked"])
        self.assertEqual(goal["outcome"], "question")
        self.assertEqual(result["questions"], 1)

    def test_a_goal_dominated_by_failures_is_reported_as_failed(self) -> None:
        records = [user("do the thing", "2026-08-01T10:00:00.000Z")]
        for index in range(3):
            call = f"t{index}"
            records.append(assistant(f"2026-08-01T10:00:0{index + 1}.000Z",
                                     [tool_use("Bash", call, command="make")], message_id=f"m{index}"))
            records.append(tool_result(call, f"2026-08-01T10:00:1{index}.000Z", error=True))
        result = self.build(records)
        self.assertEqual(result["goals"][0]["outcome"], "error")
        self.assertEqual(result["failed"], 1)

    def test_cli_scaffolding_does_not_create_a_goal(self) -> None:
        result = self.build([
            user("<system-reminder>context</system-reminder>", "2026-08-01T10:00:00.000Z"),
            user("real request", "2026-08-01T10:00:01.000Z"),
            assistant("2026-08-01T10:00:02.000Z", [tool_use("Read", "t1", file_path="/x")], message_id="m1"),
        ])
        self.assertEqual([goal["prompt"] for goal in result["goals"]], ["real request"])

    def test_work_before_the_first_prompt_is_kept_and_labelled(self) -> None:
        result = self.build([
            assistant("2026-08-01T10:00:00.000Z", [tool_use("Read", "t1", file_path="/x")], message_id="m1"),
            user("now do this", "2026-08-01T10:00:10.000Z"),
        ])
        self.assertEqual(result["goals"][0]["kind"], "implicit")
        self.assertEqual(result["goals"][0]["by_cat"], {"read": 1})

    def test_the_payload_is_bounded_no_matter_how_long_the_session_is(self) -> None:
        records = []
        for index in range(goals.MAX_GOALS + 40):
            stamp = f"2026-08-01T10:{index // 60:02d}:{index % 60:02d}.000Z"
            records.append(user(f"request {index}", stamp))
        result = self.build(records)
        self.assertEqual(len(result["goals"]), goals.MAX_GOALS)
        self.assertEqual(result["dropped"], 40)
        self.assertEqual(result["count"], goals.MAX_GOALS + 40)
        # The newest goals are the ones kept.
        self.assertEqual(result["goals"][-1]["prompt"], f"request {goals.MAX_GOALS + 39}")

    def test_steps_are_capped_per_goal_and_the_overflow_is_reported(self) -> None:
        records = [user("churn", "2026-08-01T10:00:00.000Z")]
        for index in range(goals.MAX_STEPS + 12):
            records.append(assistant("2026-08-01T10:00:01.000Z",
                                     [tool_use("Read", f"t{index}", file_path="/x")], message_id=f"m{index}"))
        goal = self.build(records)["goals"][0]
        self.assertEqual(len(goal["steps"]), goals.MAX_STEPS)
        self.assertEqual(goal["dropped_steps"], 12)
        self.assertEqual(goal["tools"], goals.MAX_STEPS + 12)

    def test_claude_goals_carry_a_price_estimate(self) -> None:
        result = self.build([
            user("spend something", "2026-08-01T10:00:00.000Z"),
            assistant("2026-08-01T10:00:02.000Z", [{"type": "text", "text": "ok"}], message_id="m1"),
        ])
        self.assertTrue(result["priced"])
        self.assertGreater(result["goals"][0]["cost"], 0)

    def test_incremental_feeding_produces_the_same_goals_as_one_pass(self) -> None:
        records = [
            user("first", "2026-08-01T10:00:00.000Z"),
            assistant("2026-08-01T10:00:02.000Z", [tool_use("Read", "t1", file_path="/x")], message_id="m1"),
            tool_result("t1", "2026-08-01T10:00:03.000Z"),
            user("second", "2026-08-01T10:01:00.000Z"),
            assistant("2026-08-01T10:01:02.000Z", [tool_use("Bash", "t2", command="ls")], message_id="m2"),
        ]
        whole = session_parser.DetailBuilder()
        for record in records:
            whole.feed(record)

        # The same records arriving in two appends, as a live session does.
        streamed = session_parser.DetailBuilder()
        for record in records[:3]:
            streamed.feed(record)
        streamed.meta()                      # a refresh happens mid-session
        for record in records[3:]:
            streamed.feed(record)

        self.assertEqual(whole.meta()["goals"], streamed.meta()["goals"])


class CodexGoalTests(unittest.TestCase):
    def build(self, records: list[dict]) -> dict:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rollout.jsonl"
            write_jsonl(path, records)
            return codex_session_parser.detail(path)["goals"]

    def test_codex_goals_are_segmented_but_never_priced(self) -> None:
        result = self.build([
            {"timestamp": "2026-08-01T10:00:00.000Z", "type": "session_meta",
             "payload": {"id": "s1", "cwd": "/repo", "context_window": 400000}},
            {"timestamp": "2026-08-01T10:00:01.000Z", "type": "event_msg",
             "payload": {"type": "user_message", "message": "make it work"}},
            {"timestamp": "2026-08-01T10:00:03.000Z", "type": "response_item",
             "payload": {"type": "function_call", "name": "shell", "call_id": "c1",
                         "arguments": json.dumps({"command": "pytest -q"})}},
            {"timestamp": "2026-08-01T10:00:20.000Z", "type": "response_item",
             "payload": {"type": "function_call_output", "call_id": "c1", "output": "ok"}},
            {"timestamp": "2026-08-01T10:00:21.000Z", "type": "event_msg",
             "payload": {"type": "token_count", "info": {"total_token_usage": {"total_tokens": 5000}}}},
        ])
        self.assertFalse(result["priced"])
        self.assertEqual(result["count"], 1)
        goal = result["goals"][0]
        self.assertEqual(goal["prompt"], "make it work")
        self.assertEqual(goal["by_cat"], {"exec": 1})
        self.assertEqual(goal["cost"], 0.0)
        self.assertEqual(goal["tokens"], 5000)

    def test_codex_scaffolding_does_not_open_a_goal(self) -> None:
        result = self.build([
            {"timestamp": "2026-08-01T10:00:00.000Z", "type": "event_msg",
             "payload": {"type": "user_message", "message": "<recommended_plugins>a list</recommended_plugins>"}},
            {"timestamp": "2026-08-01T10:00:01.000Z", "type": "event_msg",
             "payload": {"type": "user_message", "message": "an actual request"}},
        ])
        self.assertEqual([goal["prompt"] for goal in result["goals"]], ["an actual request"])


if __name__ == "__main__":
    unittest.main()
